/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaiVietRouteImport } from './routes/bai-viet'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as KeHoachRouteImport } from './routes/ke-hoach'
import { Route as LichSuRouteImport } from './routes/lich-su'
import { Route as NghiemThuRouteImport } from './routes/nghiem-thu'
import { Route as NguonDuLieuRouteImport } from './routes/nguon-du-lieu'
import { Route as TacVuNgoaiRouteImport } from './routes/tac-vu-ngoai'
import { Route as BaiVietArticleIdRouteImport } from './routes/bai-viet_.$articleId'
import { Route as DuyetArticleIdRouteImport } from './routes/duyet.$articleId'
import { Route as KeHoachBriefIdRouteImport } from './routes/ke-hoach_.$briefId'
import { Route as V1ApprovalsRouteImport } from './routes/v1/approvals'
import { Route as V1CapabilitiesRouteImport } from './routes/v1/capabilities'
import { Route as V1PublicationsRouteImport } from './routes/v1/publications'
import { Route as V1ApprovalsApproval_idRouteImport } from './routes/v1/approvals.$approval_id'
import { Route as V1ArticlesArticle_idRouteImport } from './routes/v1/articles.$article_id'
import { Route as V1BriefsBrief_idRouteImport } from './routes/v1/briefs.$brief_id'
import { Route as V1ContentJobsRouteImport } from './routes/v1/content/jobs'
import { Route as V1PlanningJobsRouteImport } from './routes/v1/planning/jobs'
import { Route as V1PublicationsPublication_idRouteImport } from './routes/v1/publications.$publication_id'
import { Route as V1ContentJobsJob_idRouteImport } from './routes/v1/content/jobs.$job_id'
import { Route as V1EvidenceBundle_idRevokeRouteImport } from './routes/v1/evidence.$bundle_id.revoke'
import { Route as V1MockLedgerRestartRouteImport } from './routes/v1/mock/ledger.restart'
import { Route as V1PlanningJobsJob_idRouteImport } from './routes/v1/planning/jobs.$job_id'
import { Route as V1PublicationsPublication_idReconcileRouteImport } from './routes/v1/publications.$publication_id.reconcile'
import { Route as V1ContentJobsJob_idCancelRouteImport } from './routes/v1/content/jobs.$job_id.cancel'
import { Route as V1ContentJobsJob_idOutputRouteImport } from './routes/v1/content/jobs.$job_id.output'
import { Route as V1PlanningJobsJob_idCancelRouteImport } from './routes/v1/planning/jobs.$job_id.cancel'
import { Route as V1PlanningJobsJob_idOutputRouteImport } from './routes/v1/planning/jobs.$job_id.output'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietRoute = BaiVietRouteImport.update({
  id: '/bai-viet',
  path: '/bai-viet',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const KeHoachRoute = KeHoachRouteImport.update({
  id: '/ke-hoach',
  path: '/ke-hoach',
  getParentRoute: () => rootRouteImport,
} as any)
const LichSuRoute = LichSuRouteImport.update({
  id: '/lich-su',
  path: '/lich-su',
  getParentRoute: () => rootRouteImport,
} as any)
const NghiemThuRoute = NghiemThuRouteImport.update({
  id: '/nghiem-thu',
  path: '/nghiem-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const NguonDuLieuRoute = NguonDuLieuRouteImport.update({
  id: '/nguon-du-lieu',
  path: '/nguon-du-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const TacVuNgoaiRoute = TacVuNgoaiRouteImport.update({
  id: '/tac-vu-ngoai',
  path: '/tac-vu-ngoai',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietArticleIdRoute = BaiVietArticleIdRouteImport.update({
  id: '/bai-viet_/$articleId',
  path: '/bai-viet/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const DuyetArticleIdRoute = DuyetArticleIdRouteImport.update({
  id: '/duyet/$articleId',
  path: '/duyet/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const KeHoachBriefIdRoute = KeHoachBriefIdRouteImport.update({
  id: '/ke-hoach_/$briefId',
  path: '/ke-hoach/$briefId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ApprovalsRoute = V1ApprovalsRouteImport.update({
  id: '/v1/approvals',
  path: '/v1/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const V1CapabilitiesRoute = V1CapabilitiesRouteImport.update({
  id: '/v1/capabilities',
  path: '/v1/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PublicationsRoute = V1PublicationsRouteImport.update({
  id: '/v1/publications',
  path: '/v1/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ApprovalsApproval_idRoute = V1ApprovalsApproval_idRouteImport.update({
  id: '/$approval_id',
  path: '/$approval_id',
  getParentRoute: () => V1ApprovalsRoute,
} as any)
const V1ArticlesArticle_idRoute = V1ArticlesArticle_idRouteImport.update({
  id: '/v1/articles/$article_id',
  path: '/v1/articles/$article_id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1BriefsBrief_idRoute = V1BriefsBrief_idRouteImport.update({
  id: '/v1/briefs/$brief_id',
  path: '/v1/briefs/$brief_id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ContentJobsRoute = V1ContentJobsRouteImport.update({
  id: '/v1/content/jobs',
  path: '/v1/content/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PlanningJobsRoute = V1PlanningJobsRouteImport.update({
  id: '/v1/planning/jobs',
  path: '/v1/planning/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PublicationsPublication_idRoute =
  V1PublicationsPublication_idRouteImport.update({
    id: '/$publication_id',
    path: '/$publication_id',
    getParentRoute: () => V1PublicationsRoute,
  } as any)
const V1ContentJobsJob_idRoute = V1ContentJobsJob_idRouteImport.update({
  id: '/$job_id',
  path: '/$job_id',
  getParentRoute: () => V1ContentJobsRoute,
} as any)
const V1EvidenceBundle_idRevokeRoute =
  V1EvidenceBundle_idRevokeRouteImport.update({
    id: '/v1/evidence/$bundle_id/revoke',
    path: '/v1/evidence/$bundle_id/revoke',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1MockLedgerRestartRoute = V1MockLedgerRestartRouteImport.update({
  id: '/v1/mock/ledger/restart',
  path: '/v1/mock/ledger/restart',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PlanningJobsJob_idRoute = V1PlanningJobsJob_idRouteImport.update({
  id: '/$job_id',
  path: '/$job_id',
  getParentRoute: () => V1PlanningJobsRoute,
} as any)
const V1PublicationsPublication_idReconcileRoute =
  V1PublicationsPublication_idReconcileRouteImport.update({
    id: '/reconcile',
    path: '/reconcile',
    getParentRoute: () => V1PublicationsPublication_idRoute,
  } as any)
const V1ContentJobsJob_idCancelRoute =
  V1ContentJobsJob_idCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => V1ContentJobsJob_idRoute,
  } as any)
const V1ContentJobsJob_idOutputRoute =
  V1ContentJobsJob_idOutputRouteImport.update({
    id: '/output',
    path: '/output',
    getParentRoute: () => V1ContentJobsJob_idRoute,
  } as any)
const V1PlanningJobsJob_idCancelRoute =
  V1PlanningJobsJob_idCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => V1PlanningJobsJob_idRoute,
  } as any)
const V1PlanningJobsJob_idOutputRoute =
  V1PlanningJobsJob_idOutputRouteImport.update({
    id: '/output',
    path: '/output',
    getParentRoute: () => V1PlanningJobsJob_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bai-viet': typeof BaiVietRoute
  '/healthz': typeof HealthzRoute
  '/ke-hoach': typeof KeHoachRoute
  '/lich-su': typeof LichSuRoute
  '/nghiem-thu': typeof NghiemThuRoute
  '/nguon-du-lieu': typeof NguonDuLieuRoute
  '/tac-vu-ngoai': typeof TacVuNgoaiRoute
  '/bai-viet/$articleId': typeof BaiVietArticleIdRoute
  '/duyet/$articleId': typeof DuyetArticleIdRoute
  '/ke-hoach/$briefId': typeof KeHoachBriefIdRoute
  '/v1/approvals': typeof V1ApprovalsRouteWithChildren
  '/v1/capabilities': typeof V1CapabilitiesRoute
  '/v1/publications': typeof V1PublicationsRouteWithChildren
  '/v1/approvals/$approval_id': typeof V1ApprovalsApproval_idRoute
  '/v1/articles/$article_id': typeof V1ArticlesArticle_idRoute
  '/v1/briefs/$brief_id': typeof V1BriefsBrief_idRoute
  '/v1/content/jobs': typeof V1ContentJobsRouteWithChildren
  '/v1/planning/jobs': typeof V1PlanningJobsRouteWithChildren
  '/v1/publications/$publication_id': typeof V1PublicationsPublication_idRouteWithChildren
  '/v1/content/jobs/$job_id': typeof V1ContentJobsJob_idRouteWithChildren
  '/v1/evidence/$bundle_id/revoke': typeof V1EvidenceBundle_idRevokeRoute
  '/v1/mock/ledger/restart': typeof V1MockLedgerRestartRoute
  '/v1/planning/jobs/$job_id': typeof V1PlanningJobsJob_idRouteWithChildren
  '/v1/publications/$publication_id/reconcile': typeof V1PublicationsPublication_idReconcileRoute
  '/v1/content/jobs/$job_id/cancel': typeof V1ContentJobsJob_idCancelRoute
  '/v1/content/jobs/$job_id/output': typeof V1ContentJobsJob_idOutputRoute
  '/v1/planning/jobs/$job_id/cancel': typeof V1PlanningJobsJob_idCancelRoute
  '/v1/planning/jobs/$job_id/output': typeof V1PlanningJobsJob_idOutputRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bai-viet': typeof BaiVietRoute
  '/healthz': typeof HealthzRoute
  '/ke-hoach': typeof KeHoachRoute
  '/lich-su': typeof LichSuRoute
  '/nghiem-thu': typeof NghiemThuRoute
  '/nguon-du-lieu': typeof NguonDuLieuRoute
  '/tac-vu-ngoai': typeof TacVuNgoaiRoute
  '/bai-viet/$articleId': typeof BaiVietArticleIdRoute
  '/duyet/$articleId': typeof DuyetArticleIdRoute
  '/ke-hoach/$briefId': typeof KeHoachBriefIdRoute
  '/v1/approvals': typeof V1ApprovalsRouteWithChildren
  '/v1/capabilities': typeof V1CapabilitiesRoute
  '/v1/publications': typeof V1PublicationsRouteWithChildren
  '/v1/approvals/$approval_id': typeof V1ApprovalsApproval_idRoute
  '/v1/articles/$article_id': typeof V1ArticlesArticle_idRoute
  '/v1/briefs/$brief_id': typeof V1BriefsBrief_idRoute
  '/v1/content/jobs': typeof V1ContentJobsRouteWithChildren
  '/v1/planning/jobs': typeof V1PlanningJobsRouteWithChildren
  '/v1/publications/$publication_id': typeof V1PublicationsPublication_idRouteWithChildren
  '/v1/content/jobs/$job_id': typeof V1ContentJobsJob_idRouteWithChildren
  '/v1/evidence/$bundle_id/revoke': typeof V1EvidenceBundle_idRevokeRoute
  '/v1/mock/ledger/restart': typeof V1MockLedgerRestartRoute
  '/v1/planning/jobs/$job_id': typeof V1PlanningJobsJob_idRouteWithChildren
  '/v1/publications/$publication_id/reconcile': typeof V1PublicationsPublication_idReconcileRoute
  '/v1/content/jobs/$job_id/cancel': typeof V1ContentJobsJob_idCancelRoute
  '/v1/content/jobs/$job_id/output': typeof V1ContentJobsJob_idOutputRoute
  '/v1/planning/jobs/$job_id/cancel': typeof V1PlanningJobsJob_idCancelRoute
  '/v1/planning/jobs/$job_id/output': typeof V1PlanningJobsJob_idOutputRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bai-viet': typeof BaiVietRoute
  '/healthz': typeof HealthzRoute
  '/ke-hoach': typeof KeHoachRoute
  '/lich-su': typeof LichSuRoute
  '/nghiem-thu': typeof NghiemThuRoute
  '/nguon-du-lieu': typeof NguonDuLieuRoute
  '/tac-vu-ngoai': typeof TacVuNgoaiRoute
  '/bai-viet_/$articleId': typeof BaiVietArticleIdRoute
  '/duyet/$articleId': typeof DuyetArticleIdRoute
  '/ke-hoach_/$briefId': typeof KeHoachBriefIdRoute
  '/v1/approvals': typeof V1ApprovalsRouteWithChildren
  '/v1/capabilities': typeof V1CapabilitiesRoute
  '/v1/publications': typeof V1PublicationsRouteWithChildren
  '/v1/approvals/$approval_id': typeof V1ApprovalsApproval_idRoute
  '/v1/articles/$article_id': typeof V1ArticlesArticle_idRoute
  '/v1/briefs/$brief_id': typeof V1BriefsBrief_idRoute
  '/v1/content/jobs': typeof V1ContentJobsRouteWithChildren
  '/v1/planning/jobs': typeof V1PlanningJobsRouteWithChildren
  '/v1/publications/$publication_id': typeof V1PublicationsPublication_idRouteWithChildren
  '/v1/content/jobs/$job_id': typeof V1ContentJobsJob_idRouteWithChildren
  '/v1/evidence/$bundle_id/revoke': typeof V1EvidenceBundle_idRevokeRoute
  '/v1/mock/ledger/restart': typeof V1MockLedgerRestartRoute
  '/v1/planning/jobs/$job_id': typeof V1PlanningJobsJob_idRouteWithChildren
  '/v1/publications/$publication_id/reconcile': typeof V1PublicationsPublication_idReconcileRoute
  '/v1/content/jobs/$job_id/cancel': typeof V1ContentJobsJob_idCancelRoute
  '/v1/content/jobs/$job_id/output': typeof V1ContentJobsJob_idOutputRoute
  '/v1/planning/jobs/$job_id/cancel': typeof V1PlanningJobsJob_idCancelRoute
  '/v1/planning/jobs/$job_id/output': typeof V1PlanningJobsJob_idOutputRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bai-viet'
    | '/healthz'
    | '/ke-hoach'
    | '/lich-su'
    | '/nghiem-thu'
    | '/nguon-du-lieu'
    | '/tac-vu-ngoai'
    | '/bai-viet/$articleId'
    | '/duyet/$articleId'
    | '/ke-hoach/$briefId'
    | '/v1/approvals'
    | '/v1/capabilities'
    | '/v1/publications'
    | '/v1/approvals/$approval_id'
    | '/v1/articles/$article_id'
    | '/v1/briefs/$brief_id'
    | '/v1/content/jobs'
    | '/v1/planning/jobs'
    | '/v1/publications/$publication_id'
    | '/v1/content/jobs/$job_id'
    | '/v1/evidence/$bundle_id/revoke'
    | '/v1/mock/ledger/restart'
    | '/v1/planning/jobs/$job_id'
    | '/v1/publications/$publication_id/reconcile'
    | '/v1/content/jobs/$job_id/cancel'
    | '/v1/content/jobs/$job_id/output'
    | '/v1/planning/jobs/$job_id/cancel'
    | '/v1/planning/jobs/$job_id/output'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bai-viet'
    | '/healthz'
    | '/ke-hoach'
    | '/lich-su'
    | '/nghiem-thu'
    | '/nguon-du-lieu'
    | '/tac-vu-ngoai'
    | '/bai-viet/$articleId'
    | '/duyet/$articleId'
    | '/ke-hoach/$briefId'
    | '/v1/approvals'
    | '/v1/capabilities'
    | '/v1/publications'
    | '/v1/approvals/$approval_id'
    | '/v1/articles/$article_id'
    | '/v1/briefs/$brief_id'
    | '/v1/content/jobs'
    | '/v1/planning/jobs'
    | '/v1/publications/$publication_id'
    | '/v1/content/jobs/$job_id'
    | '/v1/evidence/$bundle_id/revoke'
    | '/v1/mock/ledger/restart'
    | '/v1/planning/jobs/$job_id'
    | '/v1/publications/$publication_id/reconcile'
    | '/v1/content/jobs/$job_id/cancel'
    | '/v1/content/jobs/$job_id/output'
    | '/v1/planning/jobs/$job_id/cancel'
    | '/v1/planning/jobs/$job_id/output'
  id:
    | '__root__'
    | '/'
    | '/bai-viet'
    | '/healthz'
    | '/ke-hoach'
    | '/lich-su'
    | '/nghiem-thu'
    | '/nguon-du-lieu'
    | '/tac-vu-ngoai'
    | '/bai-viet_/$articleId'
    | '/duyet/$articleId'
    | '/ke-hoach_/$briefId'
    | '/v1/approvals'
    | '/v1/capabilities'
    | '/v1/publications'
    | '/v1/approvals/$approval_id'
    | '/v1/articles/$article_id'
    | '/v1/briefs/$brief_id'
    | '/v1/content/jobs'
    | '/v1/planning/jobs'
    | '/v1/publications/$publication_id'
    | '/v1/content/jobs/$job_id'
    | '/v1/evidence/$bundle_id/revoke'
    | '/v1/mock/ledger/restart'
    | '/v1/planning/jobs/$job_id'
    | '/v1/publications/$publication_id/reconcile'
    | '/v1/content/jobs/$job_id/cancel'
    | '/v1/content/jobs/$job_id/output'
    | '/v1/planning/jobs/$job_id/cancel'
    | '/v1/planning/jobs/$job_id/output'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaiVietRoute: typeof BaiVietRoute
  HealthzRoute: typeof HealthzRoute
  KeHoachRoute: typeof KeHoachRoute
  LichSuRoute: typeof LichSuRoute
  NghiemThuRoute: typeof NghiemThuRoute
  NguonDuLieuRoute: typeof NguonDuLieuRoute
  TacVuNgoaiRoute: typeof TacVuNgoaiRoute
  BaiVietArticleIdRoute: typeof BaiVietArticleIdRoute
  DuyetArticleIdRoute: typeof DuyetArticleIdRoute
  KeHoachBriefIdRoute: typeof KeHoachBriefIdRoute
  V1ApprovalsRoute: typeof V1ApprovalsRouteWithChildren
  V1CapabilitiesRoute: typeof V1CapabilitiesRoute
  V1PublicationsRoute: typeof V1PublicationsRouteWithChildren
  V1ArticlesArticle_idRoute: typeof V1ArticlesArticle_idRoute
  V1BriefsBrief_idRoute: typeof V1BriefsBrief_idRoute
  V1ContentJobsRoute: typeof V1ContentJobsRouteWithChildren
  V1PlanningJobsRoute: typeof V1PlanningJobsRouteWithChildren
  V1EvidenceBundle_idRevokeRoute: typeof V1EvidenceBundle_idRevokeRoute
  V1MockLedgerRestartRoute: typeof V1MockLedgerRestartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet': {
      id: '/bai-viet'
      path: '/bai-viet'
      fullPath: '/bai-viet'
      preLoaderRoute: typeof BaiVietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ke-hoach': {
      id: '/ke-hoach'
      path: '/ke-hoach'
      fullPath: '/ke-hoach'
      preLoaderRoute: typeof KeHoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-su': {
      id: '/lich-su'
      path: '/lich-su'
      fullPath: '/lich-su'
      preLoaderRoute: typeof LichSuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nghiem-thu': {
      id: '/nghiem-thu'
      path: '/nghiem-thu'
      fullPath: '/nghiem-thu'
      preLoaderRoute: typeof NghiemThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nguon-du-lieu': {
      id: '/nguon-du-lieu'
      path: '/nguon-du-lieu'
      fullPath: '/nguon-du-lieu'
      preLoaderRoute: typeof NguonDuLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tac-vu-ngoai': {
      id: '/tac-vu-ngoai'
      path: '/tac-vu-ngoai'
      fullPath: '/tac-vu-ngoai'
      preLoaderRoute: typeof TacVuNgoaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet_/$articleId': {
      id: '/bai-viet_/$articleId'
      path: '/bai-viet/$articleId'
      fullPath: '/bai-viet/$articleId'
      preLoaderRoute: typeof BaiVietArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duyet/$articleId': {
      id: '/duyet/$articleId'
      path: '/duyet/$articleId'
      fullPath: '/duyet/$articleId'
      preLoaderRoute: typeof DuyetArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ke-hoach_/$briefId': {
      id: '/ke-hoach_/$briefId'
      path: '/ke-hoach/$briefId'
      fullPath: '/ke-hoach/$briefId'
      preLoaderRoute: typeof KeHoachBriefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/approvals': {
      id: '/v1/approvals'
      path: '/v1/approvals'
      fullPath: '/v1/approvals'
      preLoaderRoute: typeof V1ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/capabilities': {
      id: '/v1/capabilities'
      path: '/v1/capabilities'
      fullPath: '/v1/capabilities'
      preLoaderRoute: typeof V1CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/publications': {
      id: '/v1/publications'
      path: '/v1/publications'
      fullPath: '/v1/publications'
      preLoaderRoute: typeof V1PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/approvals/$approval_id': {
      id: '/v1/approvals/$approval_id'
      path: '/$approval_id'
      fullPath: '/v1/approvals/$approval_id'
      preLoaderRoute: typeof V1ApprovalsApproval_idRouteImport
      parentRoute: typeof V1ApprovalsRoute
    }
    '/v1/articles/$article_id': {
      id: '/v1/articles/$article_id'
      path: '/v1/articles/$article_id'
      fullPath: '/v1/articles/$article_id'
      preLoaderRoute: typeof V1ArticlesArticle_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/briefs/$brief_id': {
      id: '/v1/briefs/$brief_id'
      path: '/v1/briefs/$brief_id'
      fullPath: '/v1/briefs/$brief_id'
      preLoaderRoute: typeof V1BriefsBrief_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/content/jobs': {
      id: '/v1/content/jobs'
      path: '/v1/content/jobs'
      fullPath: '/v1/content/jobs'
      preLoaderRoute: typeof V1ContentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/planning/jobs': {
      id: '/v1/planning/jobs'
      path: '/v1/planning/jobs'
      fullPath: '/v1/planning/jobs'
      preLoaderRoute: typeof V1PlanningJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/publications/$publication_id': {
      id: '/v1/publications/$publication_id'
      path: '/$publication_id'
      fullPath: '/v1/publications/$publication_id'
      preLoaderRoute: typeof V1PublicationsPublication_idRouteImport
      parentRoute: typeof V1PublicationsRoute
    }
    '/v1/content/jobs/$job_id': {
      id: '/v1/content/jobs/$job_id'
      path: '/$job_id'
      fullPath: '/v1/content/jobs/$job_id'
      preLoaderRoute: typeof V1ContentJobsJob_idRouteImport
      parentRoute: typeof V1ContentJobsRoute
    }
    '/v1/evidence/$bundle_id/revoke': {
      id: '/v1/evidence/$bundle_id/revoke'
      path: '/v1/evidence/$bundle_id/revoke'
      fullPath: '/v1/evidence/$bundle_id/revoke'
      preLoaderRoute: typeof V1EvidenceBundle_idRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/mock/ledger/restart': {
      id: '/v1/mock/ledger/restart'
      path: '/v1/mock/ledger/restart'
      fullPath: '/v1/mock/ledger/restart'
      preLoaderRoute: typeof V1MockLedgerRestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/planning/jobs/$job_id': {
      id: '/v1/planning/jobs/$job_id'
      path: '/$job_id'
      fullPath: '/v1/planning/jobs/$job_id'
      preLoaderRoute: typeof V1PlanningJobsJob_idRouteImport
      parentRoute: typeof V1PlanningJobsRoute
    }
    '/v1/publications/$publication_id/reconcile': {
      id: '/v1/publications/$publication_id/reconcile'
      path: '/reconcile'
      fullPath: '/v1/publications/$publication_id/reconcile'
      preLoaderRoute: typeof V1PublicationsPublication_idReconcileRouteImport
      parentRoute: typeof V1PublicationsPublication_idRoute
    }
    '/v1/content/jobs/$job_id/cancel': {
      id: '/v1/content/jobs/$job_id/cancel'
      path: '/cancel'
      fullPath: '/v1/content/jobs/$job_id/cancel'
      preLoaderRoute: typeof V1ContentJobsJob_idCancelRouteImport
      parentRoute: typeof V1ContentJobsJob_idRoute
    }
    '/v1/content/jobs/$job_id/output': {
      id: '/v1/content/jobs/$job_id/output'
      path: '/output'
      fullPath: '/v1/content/jobs/$job_id/output'
      preLoaderRoute: typeof V1ContentJobsJob_idOutputRouteImport
      parentRoute: typeof V1ContentJobsJob_idRoute
    }
    '/v1/planning/jobs/$job_id/cancel': {
      id: '/v1/planning/jobs/$job_id/cancel'
      path: '/cancel'
      fullPath: '/v1/planning/jobs/$job_id/cancel'
      preLoaderRoute: typeof V1PlanningJobsJob_idCancelRouteImport
      parentRoute: typeof V1PlanningJobsJob_idRoute
    }
    '/v1/planning/jobs/$job_id/output': {
      id: '/v1/planning/jobs/$job_id/output'
      path: '/output'
      fullPath: '/v1/planning/jobs/$job_id/output'
      preLoaderRoute: typeof V1PlanningJobsJob_idOutputRouteImport
      parentRoute: typeof V1PlanningJobsJob_idRoute
    }
  }
}

interface V1ApprovalsRouteChildren {
  V1ApprovalsApproval_idRoute: typeof V1ApprovalsApproval_idRoute
}

const V1ApprovalsRouteChildren: V1ApprovalsRouteChildren = {
  V1ApprovalsApproval_idRoute: V1ApprovalsApproval_idRoute,
}

const V1ApprovalsRouteWithChildren = V1ApprovalsRoute._addFileChildren(
  V1ApprovalsRouteChildren,
)

interface V1PublicationsPublication_idRouteChildren {
  V1PublicationsPublication_idReconcileRoute: typeof V1PublicationsPublication_idReconcileRoute
}

const V1PublicationsPublication_idRouteChildren: V1PublicationsPublication_idRouteChildren =
  {
    V1PublicationsPublication_idReconcileRoute:
      V1PublicationsPublication_idReconcileRoute,
  }

const V1PublicationsPublication_idRouteWithChildren =
  V1PublicationsPublication_idRoute._addFileChildren(
    V1PublicationsPublication_idRouteChildren,
  )

interface V1PublicationsRouteChildren {
  V1PublicationsPublication_idRoute: typeof V1PublicationsPublication_idRouteWithChildren
}

const V1PublicationsRouteChildren: V1PublicationsRouteChildren = {
  V1PublicationsPublication_idRoute:
    V1PublicationsPublication_idRouteWithChildren,
}

const V1PublicationsRouteWithChildren = V1PublicationsRoute._addFileChildren(
  V1PublicationsRouteChildren,
)

interface V1ContentJobsJob_idRouteChildren {
  V1ContentJobsJob_idCancelRoute: typeof V1ContentJobsJob_idCancelRoute
  V1ContentJobsJob_idOutputRoute: typeof V1ContentJobsJob_idOutputRoute
}

const V1ContentJobsJob_idRouteChildren: V1ContentJobsJob_idRouteChildren = {
  V1ContentJobsJob_idCancelRoute: V1ContentJobsJob_idCancelRoute,
  V1ContentJobsJob_idOutputRoute: V1ContentJobsJob_idOutputRoute,
}

const V1ContentJobsJob_idRouteWithChildren =
  V1ContentJobsJob_idRoute._addFileChildren(V1ContentJobsJob_idRouteChildren)

interface V1ContentJobsRouteChildren {
  V1ContentJobsJob_idRoute: typeof V1ContentJobsJob_idRouteWithChildren
}

const V1ContentJobsRouteChildren: V1ContentJobsRouteChildren = {
  V1ContentJobsJob_idRoute: V1ContentJobsJob_idRouteWithChildren,
}

const V1ContentJobsRouteWithChildren = V1ContentJobsRoute._addFileChildren(
  V1ContentJobsRouteChildren,
)

interface V1PlanningJobsJob_idRouteChildren {
  V1PlanningJobsJob_idCancelRoute: typeof V1PlanningJobsJob_idCancelRoute
  V1PlanningJobsJob_idOutputRoute: typeof V1PlanningJobsJob_idOutputRoute
}

const V1PlanningJobsJob_idRouteChildren: V1PlanningJobsJob_idRouteChildren = {
  V1PlanningJobsJob_idCancelRoute: V1PlanningJobsJob_idCancelRoute,
  V1PlanningJobsJob_idOutputRoute: V1PlanningJobsJob_idOutputRoute,
}

const V1PlanningJobsJob_idRouteWithChildren =
  V1PlanningJobsJob_idRoute._addFileChildren(V1PlanningJobsJob_idRouteChildren)

interface V1PlanningJobsRouteChildren {
  V1PlanningJobsJob_idRoute: typeof V1PlanningJobsJob_idRouteWithChildren
}

const V1PlanningJobsRouteChildren: V1PlanningJobsRouteChildren = {
  V1PlanningJobsJob_idRoute: V1PlanningJobsJob_idRouteWithChildren,
}

const V1PlanningJobsRouteWithChildren = V1PlanningJobsRoute._addFileChildren(
  V1PlanningJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaiVietRoute: BaiVietRoute,
  HealthzRoute: HealthzRoute,
  KeHoachRoute: KeHoachRoute,
  LichSuRoute: LichSuRoute,
  NghiemThuRoute: NghiemThuRoute,
  NguonDuLieuRoute: NguonDuLieuRoute,
  TacVuNgoaiRoute: TacVuNgoaiRoute,
  BaiVietArticleIdRoute: BaiVietArticleIdRoute,
  DuyetArticleIdRoute: DuyetArticleIdRoute,
  KeHoachBriefIdRoute: KeHoachBriefIdRoute,
  V1ApprovalsRoute: V1ApprovalsRouteWithChildren,
  V1CapabilitiesRoute: V1CapabilitiesRoute,
  V1PublicationsRoute: V1PublicationsRouteWithChildren,
  V1ArticlesArticle_idRoute: V1ArticlesArticle_idRoute,
  V1BriefsBrief_idRoute: V1BriefsBrief_idRoute,
  V1ContentJobsRoute: V1ContentJobsRouteWithChildren,
  V1PlanningJobsRoute: V1PlanningJobsRouteWithChildren,
  V1EvidenceBundle_idRevokeRoute: V1EvidenceBundle_idRevokeRoute,
  V1MockLedgerRestartRoute: V1MockLedgerRestartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
